### ISSUE TITLE
ResponseDto, RequestDto 아닌 Dto 제거

### ISSUE THREAD

**Issue by solpinetree** [realSolarDragons/back-end#54]
원래 `Entity` <-> `Dto` <-> `ResponseDto`, `RequestDto`
로 변환하는 것으로 로직이 형성되었었는데, Dto의 사용이 지금 과정에서는 불필요하므로 제거 하려고 합니다.

**Comment by YGwan** [comment]
어 좋은것 같아요!! 코드 확인해보니 GroupResponse와 GroupDto를 나눈 이유를 모르겠더라구요!!
해당 부분 질문하려 했는데 먼저 확인하셨군요!!

**Comment by solpinetree** [comment]
네! 원래는 Entity의 값을 모두 옮기는 객체로 사용해요!(Entity의 수정이 일어나면 안되므로) 근데 생략하는 경우도 많은 것 같아서 생략해도 될 것 같아요!
